name: NoteBlockAPI

main: com.xxmicloxx.NoteBlockAPI.NoteBlockPlayerMain
version: ${project.version}-b${BUILD_NUMBER}

description: a developer interface to play nbs-files ingame
authors: [xxmicloxx, michidk]